### ISSUE TITLE
AltJit activation fails: Syntax error

### ISSUE THREAD

**Issue by KnechtNoobrecht** [rileytestut/AltStore#1315]
Error Description
The process 'altjit' failed with code 1. Could not connect to device (redacted ID). The process 'python3' returned unexpected output. SyntaxError: invalid syntax

Failure Reason
The process 'altjit' failed with code 1. Could not connect to device (redacted ID). The process 'python3' returned unexpected output. SyntaxError: invalid syntax

Title
JIT could not be enabled for UTM.

Source Line
61

executableURL
file:///Applications/AltServer.app/Contents/MacOS/altjit

exitCode
1

output
```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/julius/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 8, in <module>
    from pymobiledevice3.cli.activation import cli as activation_cli
  File "/Users/julius/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/activation.py", line 3, in <module>
    from pymobiledevice3.cli.cli_common import Command
  File "/Users/julius/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 16, in <module>
    from pymobiledevice3.lockdown import LockdownClient, create_using_usbmux
  File "/Users/julius/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/lockdown.py", line 24, in <module>
    from pymobiledevice3.lockdown_service_provider import LockdownServiceProvider
  File "/Users/julius/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/lockdown_service_provider.py", line 6, in <module>
    from pymobiledevice3.service_connection import LockdownServiceConnection
  File "/Users/julius/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/service_connection.py", line 1, in <module>
    import asyncio
  File "/Users/julius/Library/Python/3.9/lib/python/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/Users/julius/Library/Python/3.9/lib/python/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
```

❌ Unable to enable JIT for UTM on device (redacted ID).
Could not connect to device (redacted ID). The process 'python3' returned unexpected output. SyntaxError: invalid syntax

This error occurs when i try to enable AltJit via GUI. Device is connected via USB-C, macOS 14.0, iPadOS 17.0.3, AltServer 1.7, pymobiledevice3 installed, python3 version is 3.10.13. Xcode as well as Xcode command line tools are also installed.

**Comment by shanegillio** [comment]
Do you know if this is only happening when you try to enable for UTM? If you don't have any other apps, you can try just enabling for AltStore and see if the error still occurs.

**Comment by KnechtNoobrecht** [comment]
It happens for every app i try, so UTM, PojavLauncher and AltStore to be specific.

**Comment by NethercraftMC5608** [comment]
This is caused by having asyncio installed or a module that conflicts with it.

So simply remove asyncio by doing:
`python3 -m pip uninstall asyncio`
And it should work!
