### ISSUE TITLE
Crash everytime I tried to play

### ISSUE THREAD

**Issue by Tataridayo** [rileytestut/AltStore#1422]
[Pre-Init] PojavLauncher INIT!
[Pre-Init] Version: 2.2-development
[Pre-Init] Commit: d9877bc (main)
[Pre-Init] Device: iPhone 13
[Pre-Init] iOS 17.4.1 (Unjailbroken)
[Pre-init] Entitlements availability:
* com.apple.developer.kernel.extended-virtual-addressing: NO
* com.apple.developer.kernel.increased-memory-limit: NO
* com.apple.private.security.no-sandbox: NO
* dynamic-codesigning: NO
[Debugging] Debug log enabled: YES
[Pre-init] Restored game directory preference (default)
2024-04-14 20:42:36.030 PojavLauncher[4507:469675] *** Assertion failure in -[UISplitViewControllerPanelImpl _effectiveTargetDisplayMode], UISplitViewControllerPanelImpl.m:8092
[MCDL] Downloading 1.20.4
[MCDL] SHA1 passed for 1.20.4.json
[MCDL] Downloading 12
[MCDL] SHA1 passed for 12.json
[MCDL] Begin: download libraries
[MCDL] SHA1 passed for java-objc-bridge-1.1.jar
[MCDL] SHA1 passed for oshi-core-6.4.5.jar
[MCDL] SHA1 passed for gson-2.10.1.jar
[MCDL] SHA1 passed for failureaccess-1.0.1.jar
[MCDL] SHA1 passed for guava-32.1.2-jre.jar
[MCDL] SHA1 passed for icu4j-73.2.jar
[MCDL] SHA1 passed for authlib-6.0.52.jar
[MCDL] SHA1 passed for blocklist-1.0.10.jar
[MCDL] SHA1 passed for brigadier-1.2.9.jar
[MCDL] SHA1 passed for datafixerupper-6.0.8.jar
[MCDL] SHA1 passed for logging-1.1.1.jar
[MCDL] SHA1 passed for patchy-2.2.10.jar
[MCDL] SHA1 passed for text2speech-1.17.9.jar
[MCDL] SHA1 passed for commons-codec-1.16.0.jar
[MCDL] SHA1 passed for commons-io-2.13.0.jar
[MCDL] SHA1 passed for commons-logging-1.2.jar
[MCDL] SHA1 passed for netty-buffer-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-codec-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-common-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-handler-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-resolver-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-classes-epoll-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
[MCDL] SHA1 passed for netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar
[MCDL] SHA1 passed for netty-transport-native-unix-common-4.1.97.Final.jar
[MCDL] SHA1 passed for netty-transport-4.1.97.Final.jar
[MCDL] SHA1 passed for fastutil-8.5.12.jar
[MCDL] SHA1 passed for jna-platform-5.13.0.jar
[MCDL] SHA1 passed for jna-5.13.0.jar
[MCDL] SHA1 passed for jopt-simple-5.0.4.jar
[MCDL] SHA1 passed for commons-compress-1.22.jar
[MCDL] SHA1 passed for commons-lang3-3.13.0.jar
[MCDL] SHA1 passed for httpclient-4.5.13.jar
[MCDL] SHA1 passed for httpcore-4.4.16.jar
[MCDL] SHA1 passed for log4j-api-2.19.0.jar
[MCDL] SHA1 passed for log4j-core-2.19.0.jar
[MCDL] SHA1 passed for log4j-slf4j2-impl-2.19.0.jar
[MCDL] SHA1 passed for joml-1.10.5.jar
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.2:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-macos-arm64
[MCDL] SHA1 passed for slf4j-api-2.0.7.jar
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.2:natives-windows-x86
[MCDL] SHA1 passed for 1.20.4.jar
[MCDL] Finished: download libraries
[MCDL] Begin: download assets
[MCDL] SHA1 passed for 3795/3796 asset files
[MCDL] Finished: download assets
Note: some files of 1.19+ are skipped to workaround an issue
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/versions/1.20.4/1.20.4.json, have to assume it's good.
[MCDL] SHA1 passed for 12.json
[JavaLauncher] Beginning JVM launch
[JavaLauncher] Attempting to change to Java 17 (actual might be higher)
[JavaLauncher] JAVA_HOME is now set to /var/containers/Bundle/Application/A12D81EC-8EED-4B45-977B-144F84FAA544/App.app/java_runtimes/java-17-openjdk
[JavaLauncher] Restored preference: RENDERER is set to auto
[JavaLauncher] Max RAM allocation is set to 905 MB
[Init] Found JLI lib
[Init] Calling JLI_Launch
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
Launching Minecraft 1.20.4
Ignored non-exists file: /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
Args init finished. Now starting game
2024-04-14 20:43:47,564 main ERROR appender Console has no parameter that matches element Policies
[20:43:47] [main/WARN]: Failed sysctl call: hw.packages, Error code: 1
[20:43:47] [main/WARN]: Failed sysctl call: machdep.cpu.brand_string, Error code: 1
[20:43:47] [main/WARN]: Failed sysctl call: machdep.cpu.vendor, Error code: 2
[20:43:47] [main/WARN]: Failed sysctl call: machdep.cpu.stepping, Error code: 2
[20:43:47] [main/WARN]: Failed sysctl call: machdep.cpu.model, Error code: 2
[20:43:47] [main/WARN]: Failed sysctl call: machdep.cpu.family, Error code: 2
[20:43:47] [main/WARN]: Failed sysctl call: machdep.cpu.signature, Error code: 2
[20:43:47] [main/WARN]: Failed sysctl call: machdep.cpu.feature_bits, Error code: 2
[20:43:47] [main/WARN]: Failed sysctl call: vm.swapusage, Error code: 1
[20:43:49] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 108 milliseconds
[20:43:50] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[20:43:50] [Render thread/INFO]: Setting user: Tataridayo
[20:43:50] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[20:43:50] [Render thread/WARN]: Failed sysctl call: hw.packages, Error code: 1
[20:43:50] [Render thread/WARN]: Failed sysctl call: machdep.cpu.brand_string, Error code: 1
[20:43:50] [Render thread/WARN]: Failed sysctl call: machdep.cpu.vendor, Error code: 2
[20:43:50] [Render thread/WARN]: Failed sysctl call: machdep.cpu.stepping, Error code: 2
[20:43:50] [Render thread/WARN]: Failed sysctl call: machdep.cpu.model, Error code: 2
[20:43:50] [Render thread/WARN]: Failed sysctl call: machdep.cpu.family, Error code: 2
[20:43:50] [Render thread/WARN]: Failed sysctl call: machdep.cpu.signature, Error code: 2
[20:43:50] [Render thread/WARN]: Failed sysctl call: machdep.cpu.feature_bits, Error code: 2
[20:43:50] [Render thread/WARN]: Failed sysctl call: vm.swapusage, Error code: 1
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-04-14 20:43:50
Description: Initializing game

java.lang.ExceptionInInitializerError
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.lang.System.getProperty(String)" is null
	at org.lwjgl.opengl.GL.<clinit>(GL.java:81)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Mac OS X (aarch64) version 17.4.1
	Java Version: 17.0.8-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 335221832 bytes (319 MiB) / 614465536 bytes (586 MiB) up to 956301312 bytes (912 MiB)
	CPUs: 6
	Processor Vendor: 
	Processor Name: 
	Identifier:  Family  Model  Stepping 
	Microarchitecture: unknown
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 3621.94
	Virtual memory used (MB): 2845.44
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -Xms128M -Xmx905M -Xbootclasspath/a:/var/containers/Bundle/Application/A12D81EC-8EED-4B45-977B-144F84FAA544/App.app/libs_caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/var/containers/Bundle/Application/A12D81EC-8EED-4B45-977B-144F84FAA544/App.app/libs_caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar -XX:-UseCompressedClassPointers
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_JP
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /var/mobile/Containers/Data/Application/112A626A-C057-43BF-9F7A-A12E4230F20C/Documents/Library/Application Support/minecraft/crash-reports/crash-2024-04-14_20.43.50-client.txt
exit(-1) called

Why its keep happening?

**Comment by Tataridayo** [comment]
It was PojavLauncher issue
