### ISSUE TITLE
This is what happened to mine

### ISSUE THREAD

**Issue by devourofcosmos** [rileytestut/AltStore#1445]
Error Description
The process 'altjit' failed with code 1. Could not connect to device 00008130-001E49880883401C. The process 'python3' returned unexpected output. KeyError: <Epoch.INITIAL: 0>

Failure Reason
The process 'altjit' failed with code 1. Could not connect to device 00008130-001E49880883401C. The process 'python3' returned unexpected output. KeyError: <Epoch.INITIAL: 0>

Title
JIT could not be enabled for UTM.

Source Line
61

executableURL
file:///Applications/AltServer.app/Contents/MacOS/altjit

exitCode
1

output
/Users/buc/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/client.py", line 95, in connect
    protocol.connect(addr)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/protocol.py", line 60, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/quic/connection.py", line 504, in connect
    self._connect(now=now)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/quic/connection.py", line 1217, in _connect
    self._initialize(self._peer_cid.cid)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/quic/connection.py", line 1373, in _initialize
    raise RuntimeError(
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 148, in <module>
    main()
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 108, in wrapper
    func(*args, **kwargs)
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/remote.py", line 159, in cli_start_quic_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout), debug=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/remote.py", line 97, in tunnel_task
    async with start_quic_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout) as tunnel_result:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 592, in start_quic_tunnel
    async with service.start_quic_tunnel(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 249, in start_quic_tunnel
    async with aioquic_connect(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/client.py", line 100, in connect
    protocol.close()
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/protocol.py", line 52, in close
    self.transmit()
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/protocol.py", line 102, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
  File "/Users/buc/Library/Python/3.9/lib/python/site-packages/qh3/quic/connection.py", line 541, in datagrams_to_send
    crypto = self._cryptos[epoch]
KeyError: <Epoch.INITIAL: 0>

❌ Unable to enable JIT for UTM on device 00008130-001E49880883401C.
Could not connect to device 00008130-001E49880883401C. The process 'python3' returned unexpected output. KeyError: <Epoch.INITIAL: 0>

**Comment by yeweiyang96** [comment]
https://github.com/altstoreio/AltStore/issues/1345#issuecomment-2068895007
