### ISSUE TITLE
JIT could not be enabled(iOS18.2)

### ISSUE THREAD

**Issue by checion** [rileytestut/AltStore#1542]
The process 'altjit' failed with code 1. Could not connect to device 00008110-0015191226E2401E. The process 'python3' returned unexpected output. ConnectionError
OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 148, in <module>
    main()
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 108, in wrapper
    func(*args, **kwargs)
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/remote.py", line 159, in cli_start_quic_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout), debug=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/remote.py", line 97, in tunnel_task
    async with start_quic_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout) as tunnel_result:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 592, in start_quic_tunnel
    async with service.start_quic_tunnel(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 249, in start_quic_tunnel
    async with aioquic_connect(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/client.py", line 97, in connect
    await protocol.wait_connected()
  File "/Users/checio/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError

❌ Unable to enable JIT for LiveContainer_PleaseDoNotShortenTheExecutableNameBecauseItIsUsedToReserveSpaceForOverwritingThankYou on device 00008110-0015191226E2401E.
Could not connect to device 00008110-0015191226E2401E. The process 'python3' returned unexpected output. ConnectionError

**Comment by JiatengAllen** [comment]
you can find something at faq.altstore.io
