### ISSUE TITLE
AltJIT Failing with ConnectionError

### ISSUE THREAD

**Issue by CooperCorona** [rileytestut/AltStore#1545]
I'm trying to enable JIT on DolphiniOS. I [followed the instructions](https://faq.altstore.io/altstore-classic/altjit#ios-17-instructions-macos-only), but I kept getting an error. I tried a variety of troubleshooting steps, which changed which error I got, but it did not change the error. I

* Installed `openssl@3` using Homebrew.
* I ran `python3 -m pip install pymobiledevice3==2.30.0 construct==2.10.69 qh3==0.15.1` according to #1497. This fixed the "LibreSSL" error and the error from that issue. 
* Installed DolphiniOS, and selected it in the AltServer > Enable JIT menu.

However, now I'm getting
```The process 'altjit' failed with code 1. Could not connect to device 00008110-001838D90AEA401E. The process 'python3' returned unexpected output. ConnectionError```

[Full error at this Gist](https://gist.github.com/CooperCorona/a5ea516159a94637cb788179ca101bd4).

Some posts say to run the Python commands directly, but when I run `python3 -m pymobiledevice3 remote start-quic-tunnel --script-mode`, I get the same error. Furthermore, this seems to break the connection to my device. I can't run anything in Xcode, getting a "Waiting for iPad to connect", until I restart both devices.

Versions:
* MacOS Sequoia 15.2
* iPadOS 18.2
* iPad Mini 6th Gen

**Comment by CardiganDisaster** [comment]
Hello! I have been getting this same exact error whenever I try enabling AltJit for Dolphin iOS ever since I updated to iOS 18.2 on my iPhone as well! Were you ever able to figure out a fix?

I finally was forced to update from iOS 16 to iOS 18, which I knew would cause some issues but this one has me stuck. I've followed every guide possible and was getting an `<Epoch.INITIAL: 0>` error. That lead me to this thread #1345 (which was super helpful for all the other issues I had) and the same `python3 -m pip install pymobiledevice3==2.30.0 construct==2.10.69 qh3==0.15.1` fix you mentioned.

I thought that was going to be the end of it, but now I'm stuck with the connection error :( any help would be appreciated!

My devices
- MacOS Sonoma 14.7.2
- iOS 18.2
- iPhone 14 Pro Max

**Comment by rmGFW** [comment]
I'm having a similar issue, 
```txt
Error Description
The process 'altjit' failed with code 1. Could not connect to device 000xxxx0-000xxxxx1001C. The process 'python3' returned unexpected output. Error: No such command 'start-quic-tunnel'.

Failure Reason
The process 'altjit' failed with code 1. Could not connect to device 000xxxx0-000xxxxx1001C. The process 'python3' returned unexpected output. Error: No such command 'start-quic-tunnel'.

Title
JIT could not be enabled for UTM.

Source Line
61

executableURL
file:///Applications/AltServer.app/Contents/MacOS/altjit

exitCode
1

output
/Users/leo/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Usage: python -m pymobiledevice3 remote [OPTIONS] COMMAND [ARGS]...
Try 'python -m pymobiledevice3 remote -h' for help.
Error: No such command 'start-quic-tunnel'.

❌ Unable to enable JIT for UTM on device 000xxxx0-000xxxxx1001C.
Could not connect to device 000xxxx0-000xxxxx1001C. The process 'python3' returned unexpected output. Error: No such command 'start-quic-tunnel'.
```

**Comment by jonreyno** [comment]
Also getting the same error as @CooperCorona and @CardiganDisaster after following the same steps to fix the other qh3 error.

Versions:
- MacOS Sequoia 15.2
- iOS 18.2
- iPhone 12 Pro Max

**Comment by doublegate** [comment]
Same here, as well.  iOS 18.2.1, trying on both iPhone 15 Pro and iPad Pro (M4) using MacOS Sequoia and all available suggestions / fixes on GitHub and Reddit ... no-joy.

" ... The process 'altjit' failed with code 1. Could not connect to device 00008110-001838D90AEA401E. The process 'python3' returned unexpected output. ConnectionError ..."

**Comment by Nicba1010** [comment]
Same issue, iPhone 13 Pro Max, newest ios, M4 Pro Macbook

**Comment by aabanic** [comment]
Also confirmed on iPhone 13 Pro Max, Newest iOS, M1 Pro Macbook

```
Error Description
The process 'altjit' failed with code 1. Could not connect to device 00008110-00180D0A0E0A801E. The process 'python3' returned unexpected output. ConnectionError

Failure Reason
The process 'altjit' failed with code 1. Could not connect to device 00008110-00180D0A0E0A801E. The process 'python3' returned unexpected output. ConnectionError

Title
JIT could not be enabled for PojavLauncher.

Source Line
61

executableURL
file:///Applications/AltServer.app/Contents/MacOS/altjit

exitCode
1

output
/Users/ana/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 148, in <module>
    main()
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/__main__.py", line 100, in main
    cli()
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/cli_common.py", line 108, in wrapper
    func(*args, **kwargs)
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/remote.py", line 159, in cli_start_quic_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout), debug=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/cli/remote.py", line 97, in tunnel_task
    async with start_quic_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout) as tunnel_result:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 592, in start_quic_tunnel
    async with service.start_quic_tunnel(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 249, in start_quic_tunnel
    async with aioquic_connect(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/client.py", line 97, in connect
    await protocol.wait_connected()
  File "/Users/ana/Library/Python/3.9/lib/python/site-packages/qh3/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError

❌ Unable to enable JIT for PojavLauncher on device 00008110-00180D0A0E0A801E.
Could not connect to device 00008110-00180D0A0E0A801E. The process 'python3' returned unexpected output. ConnectionError

```

**Comment by aabanic** [comment]
I suppose it has to do with this https://github.com/nexron171/SimVirtualLocation/issues/20

**Comment by CardiganDisaster** [comment]
@aabanic That's good to finally know what the problem is with iOS 18.2.

Do we know of a way to switch over to a TCP tunnel instead of a QUIC one using the 2.30.0 version of pymobiledevice3 we need for Altserver?

**Comment by Nicba1010** [comment]
@CardiganDisaster  That was me posting from my wife's account, was trying on her laptop. Well first off it seems Python 3.13 is needed if the message is to be believed. `start-tunnel` command is not available in 2.30.0. What is the reason 2.30.0 is the only one that works in altstore?

**Comment by Dewl123** [comment]
I aswell have this connection problem, but cannot work on it to find a solution since its not my Mac I’m using and therefore I cannot troubleshoot much, so I would appreciate it if someone could notify me or something, I don’t use this site often so not quite sure how it works😅

iPhone 16 Pro Max iOS 18.3.1
MacBook m1 i believe, but not mine so not sure

**Comment by MR-UNI** [comment]
I too have the same problem and have been since i think ipadOS 17.2 , I have tried literally everything, pipx, --break-system-packages, giving altserver all of the permissions i can posibly give it in macOS, changing the versions of python3 and pymobiledevice3, starting the tunnel myself- ect... I am at a loss-

iPad Pro M1- iPadOS 18.3
Macbook Pro M3 Pro- MacOS Sequoia 15.3
